### ISSUE TITLE
can't download the games

### ISSUE THREAD

**Issue by dreygillan1** [Bob123a1/CDNSP-GUI#78]
what should i do, continues to appear, this error when i try to download any game.

![capturar](https://user-images.githubusercontent.com/45043344/48496257-ca8e9080-e818-11e8-9084-2dc595d0b3cf.JPG)

**Comment by shlv3r** [comment]
hello, 
same error for me

**Comment by acsizer** [comment]
Hi the same error for me. 😣 somebody help.plz

**Comment by acsizer** [comment]
Hi  After you click on download
 it says check downloading process in cmd 

a moment after that it says download 
finished and this error appears

**Comment by Bob123a1** [comment]
Downloading game files isn't available anymore for the public, Nintendo has made it not possible to share certs.

**Comment by GitHubNoobie** [comment]
> Downloading game files isn't available anymore for the public, Nintendo has made it not possible to share certs.

Hello, even from other websites ? or torrents ?

**Comment by karnacle** [comment]
No issue today ? to progress?

**Comment by acsizer** [comment]
Hi .no thanks Got any news about CDnsp


از گوشی هوشمند Samsung Galaxy ارسال شده است.
-------- پیام اصلی --------از: karnacle <notifications@github.com> تاریخ: ۲۰۱۹/۱/۶  ۱۹:۳۷  (GMT+03:30) گیرنده: Bob123a1/CDNSP-GUI <CDNSP-GUI@noreply.github.com> گیرنده کپی: acsizer <pokken_dx_75@yahoo.com>, Comment <comment@noreply.github.com> موضوع: Re: [Bob123a1/CDNSP-GUI] can't download the games (#78) 
No issue today ? to progress?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Bob123a1/CDNSP-GUI","title":"Bob123a1/CDNSP-GUI","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Bob123a1/CDNSP-GUI"}},"updates":{"snippets":[{"icon":"PERSON","message":"@karnacle in #78: No issue today ? to progress?"}],"action":{"name":"View Issue","url":"https://github.com/Bob123a1/CDNSP-GUI/issues/78#issuecomment-451753210"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Bob123a1/CDNSP-GUI/issues/78#issuecomment-451753210",
"url": "https://github.com/Bob123a1/CDNSP-GUI/issues/78#issuecomment-451753210",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
